// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmtemxfstvghtryoqpnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdGVteGZzdHZnaHRyeW9xcG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTc5MjIsImV4cCI6MjA3MDMzMzkyMn0.k1W3KfHn1rYaA1dk0pMoxZ5f3A48sI8rQ_2TzHBN1cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});